#!/usr/bin/env python3
"""
Generate regulation-focused documentation pages from SBS benchmark markdown files.
"""

from collections import OrderedDict
from pathlib import Path
import re

from generate_xml import parse_markdown_file

REGULATIONS = [
    ("HIPAA", "hipaa"),
    ("GDPR", "gdpr"),
    ("NIST", "nist"),
    ("CCPA/CPRA", "ccpa-cpra"),
    ("SOC 2", "soc-2"),
    ("ISO 27001", "iso-27001"),
]

RISK_BADGE_TYPES = {
    "Critical": "danger",
    "High": "warning",
    "Moderate": "tip",
}
RISK_TEXT_RE = re.compile(r'<Badge\s+type="[^"]+"\s+text="(?P<risk>Critical|High|Moderate)"\s*/>')


def load_all_controls(benchmark_dir: Path):
    """Load all controls from benchmark markdown files."""
    controls = []
    for md_file in sorted(benchmark_dir.glob("*.md")):
        controls.extend(parse_markdown_file(md_file))
    return controls


def extract_risk_level(risk_content: str):
    """Extract the risk level directly from markdown badge markup."""
    if not risk_content:
        return ""

    match = RISK_TEXT_RE.search(risk_content)
    if not match:
        return ""

    return match.group("risk")


def enrich_controls(controls):
    """Attach derived fields used by the generated regulation pages."""
    for control in controls:
        control["risk_level"] = extract_risk_level(control.get("risk", ""))


def build_regulation_index(controls):
    """Group controls by regulation while preserving benchmark section order."""
    grouped = {name: OrderedDict() for name, _slug in REGULATIONS}

    for control in controls:
        for regulation in control.get("regulations", []):
            name = regulation.get("name")
            if name not in grouped:
                continue

            category = control.get("category", "Uncategorized")
            grouped[name].setdefault(category, []).append(control)

    return grouped


def render_risk_badge(risk_level: str):
    """Render VitePress risk badge markup when metadata is available."""
    if risk_level not in RISK_BADGE_TYPES:
        return ""
    return f'<Badge type="{RISK_BADGE_TYPES[risk_level]}" text="{risk_level}" />'


def build_header(title: str):
    return "\n".join(
        [
            "---",
            f"title: {title}",
            "---",
            "",
            "<!-- This file is generated by scripts/generate_regulation_pages.py. -->",
            "",
        ]
    )


def render_regulation_page(regulation_name: str, categories: OrderedDict):
    """Render a markdown page for a single regulation."""
    total_controls = sum(len(controls) for controls in categories.values())
    lines = [
        build_header(f"{regulation_name} Controls"),
        f"# {regulation_name} Controls",
        "",
        (
            "This page lists SBS controls tagged for this regulation or framework. "
            "The mappings are indicative only and help readers identify controls that "
            "directly support demonstrating compliance."
        ),
        "",
        (
            "These entries are an index into the benchmark. The canonical control "
            "content remains on the benchmark pages."
        ),
        "",
        f"- Total tagged controls: **{total_controls}**",
        f"- Benchmark sections represented: **{len(categories)}**",
        "",
        "## Controls By Benchmark Section",
        "",
    ]

    if not total_controls:
        lines.extend(
            [
                f"No controls are currently tagged for `{regulation_name}`.",
                "",
            ]
        )
        return "\n".join(lines)

    for category, controls in categories.items():
        lines.extend(
            [
                f"## {category}",
                "",
                f"{len(controls)} control(s) in this benchmark section.",
                "",
            ]
        )

        for control in controls:
            title = control.get("title", "")
            control_id = control.get("id", "")
            statement = control.get("statement", "")
            source_path = control.get("source_path", "")
            risk_level = control.get("risk_level", "")
            risk_badge = render_risk_badge(risk_level)
            rationale = ""
            for regulation in control.get("regulations", []):
                if regulation.get("name") == regulation_name:
                    rationale = regulation.get("rationale", "")
                    break

            lines.extend(
                [
                    f"### {control_id}: {title}",
                    "",
                    (f"{risk_badge} " if risk_badge else "") + f"[Source page]({source_path})",
                    "",
                    f"**Control Statement:** {statement}",
                    "",
                ]
            )

            if rationale:
                lines.extend(
                    [
                        f"**Why tagged:** {rationale}",
                        "",
                    ]
                )

    return "\n".join(lines)


def render_index_page(regulation_pages, grouped_controls):
    """Render the regulations landing page."""
    lines = [
        build_header("Regulations"),
        "# Regulations",
        "",
        (
            "This section groups SBS controls by regulation and framework tags such as "
            "`NIST`, `GDPR`, and `ISO 27001`."
        ),
        "",
        (
            "These mappings are indicative only. They help readers browse the benchmark "
            "through a compliance lens, but they do not replace a formal gap assessment "
            "or direct review of the underlying framework requirements."
        ),
        "",
        "## Available Views",
        "",
        "| Regulation | Tagged Controls | Page |",
        "|------------|----------------:|------|",
    ]

    for regulation_name, slug in regulation_pages:
        total_controls = sum(len(controls) for controls in grouped_controls[regulation_name].values())
        lines.append(
            f"| {regulation_name} | {total_controls} | [View page](/regulations/{slug}) |"
        )

    lines.extend(
        [
            "",
            "## How To Use These Pages",
            "",
            "- Use each regulation page as an index into the benchmark, not as a replacement for the benchmark pages.",
            "- Each listed control links back to its canonical benchmark section.",
            "- Untagged controls are intentionally excluded from these views.",
            "",
        ]
    )
    return "\n".join(lines)


def write_pages(output_dir: Path, grouped_controls):
    """Write the regulations landing page and individual regulation pages."""
    output_dir.mkdir(parents=True, exist_ok=True)

    index_content = render_index_page(REGULATIONS, grouped_controls)
    (output_dir / "index.md").write_text(index_content + "\n", encoding="utf-8")

    for regulation_name, slug in REGULATIONS:
        page_content = render_regulation_page(regulation_name, grouped_controls[regulation_name])
        (output_dir / f"{slug}.md").write_text(page_content + "\n", encoding="utf-8")


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    benchmark_dir = repo_root / "benchmark"
    output_dir = repo_root / "regulations"

    controls = load_all_controls(benchmark_dir)
    enrich_controls(controls)
    grouped_controls = build_regulation_index(controls)
    write_pages(output_dir, grouped_controls)

    total_regulation_controls = sum(
        sum(len(controls) for controls in categories.values())
        for categories in grouped_controls.values()
    )
    print(f"Parsed {len(controls)} controls.")
    print(f"Wrote regulation pages to: {output_dir}")
    print(f"Total tagged control entries across all regulations: {total_regulation_controls}")


if __name__ == "__main__":
    main()
